### ISSUE TITLE
Unable to set up integration [cloud][BB160]

### ISSUE THREAD

**Issue by bilak** [JurajNyiri/HomeAssistant-Atrea#6]
Hello,
I'm trying to set up this integration. 

I'm using the Atreas cloud (I'm living in apartment not in house) and unit BB160. Probably the problem could be also that in cloud the username is required, but I can't find a way how to pass it. I guess that name in configuration bellow is for climate name (e.g. prefix).

my config is as follows:

```yaml
climate:
- platform: atrea
  host: !secret atrea_host
  password: !secret atrea_password
  #name: !secret atrea_user
  customize:
    presets:
    - 'Off'
    - 'Automat'
    - 'Ventilation'
    - 'Disbalance'
```

when I restart the HA I'm getting following error:

```
Error adding entities for domain climate with platform atrea
Error while setting up atrea platform for climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 540, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 302, in state_attributes
    data[ATTR_PRESET_MODE] = self.preset_mode
  File "/config/custom_components/atrea/climate.py", line 196, in preset_mode
    if self._current_preset.name and self._current_preset.name in self._userLabels:
AttributeError: 'NoneType' object has no attribute 'name'
```

could you please help me to resolve the issue if possible?

Thanks

**Comment by JurajNyiri** [comment]
Hello,

only local configuration is supported with this integration.

**Comment by bilak** [comment]
any chance to support cloud when I would be a tester?

**Comment by JurajNyiri** [comment]
It's impossible for me to add support without an actual unit to test on. If you would provide me access to your unit I could take a look ( juraj.nyiri@gmail.com ), or someone else needs to code in the necessary changes.

**Comment by JurajNyiri** [comment]
I do not want to support cloud as it is a lot trickier with laws, if the API is not publicly available and documented. 
If someone wants to fork this and add support for cloud, provided he has permission feel free to do so.
