### ISSUE TITLE
Cannot load after update from 5.0.1 to 6.0.3

### ISSUE THREAD

**Issue by rnovacek** [JurajNyiri/HomeAssistant-Atrea#9]
The extension was working fine in 5.0.1, but doesn't load with 6.0.3. I've deleted the configuration in Home Assistant config file and used UI to set it up again and it doesn't show any devices/entities. The log file has following error message:

```
Error while setting up atrea platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/atrea/climate.py", line 66, in async_setup_entry
    hass.data[DOMAIN][entry.entry_id]["climate"] = AtreaDevice(
  File "/config/custom_components/atrea/climate.py", line 103, in __init__
    self.manualUpdate(False)
  File "/config/custom_components/atrea/climate.py", line 269, in manualUpdate
    self._model = self.atrea.getModel()
  File "/config/deps/lib/python3.9/site-packages/pyatrea/__init__.py", line 152, in getModel
    configDir = self.getConfigDir()
  File "/config/deps/lib/python3.9/site-packages/pyatrea/__init__.py", line 132, in getConfigDir
    response = requests.get(
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1296, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 219, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 173, in protected_loop_func
    check_loop(func, strict=strict)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 161, in check_loop
    raise RuntimeError(
RuntimeError: Blocking calls must be done in the executor or a separate thread; Use `await hass.async_add_executor_job()` at custom_components/atrea/climate.py, line 269: self._model = self.atrea.getModel()
```

HomeAssistant version: 2022.5.5

**Comment by JurajNyiri** [comment]
Fixed in https://github.com/JurajNyiri/HomeAssistant-Atrea/releases/tag/6.1.0 .
